import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {dirname,extname,join,normalize} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';

const root=dirname(fileURLToPath(import.meta.url));
const dataFile=join(root,'data','worldtiers.json');
const dist=join(root,'dist');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon','.json':'application/json; charset=utf-8'};
const send=(res,status,body,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body))};
const readDb=async()=>JSON.parse(await readFile(dataFile,'utf8'));
const saveDb=async data=>{await mkdir(dirname(dataFile),{recursive:true});await writeFile(dataFile,JSON.stringify(data,null,2)+'\n')};
const ipOf=req=>(req.headers['x-forwarded-for']?.split(',')[0].trim()||req.socket.remoteAddress||'').replace(/^::ffff:/,'');
const isLocal=ip=>ip==='127.0.0.1'||ip==='::1';
const validUsername=value=>/^[a-zA-Z0-9_]{3,16}$/.test(value);
const validUuid=value=>/^[a-f0-9]{32}$/.test(value);
const tierPoints={HT1:60,LT1:45,HT2:30,LT2:20,HT3:10,LT3:6,HT4:4,LT4:3,HT5:2,LT5:1};
const updatePoints=player=>{player.points=Object.values(player.tiers||{}).reduce((total,tier)=>total+(tierPoints[tier]||0),0)};
const modeIds=['crystal','sword','uhc','nethpot','pot','smp','axe','diasmp','mace','spear-mace'];
const apiDocs={name:'WorldTiers API',version:'1.0.0',message:'Choisis une route dans cette liste.',endpoints:{health:'/api/health',players:'/api/players',top100:'/api/top100',stats:'/api/stats',modes:'/api/modes',player:'/api/user/:username',mode:'/api/:mode',modePlayer:'/api/:mode/user/:username',minecraftUuid:'/api/minecraft/:username'}};
const cleanPlayer=player=>({id:player.id,username:player.username,minecraft_uuid:player.minecraft_uuid,skinHash:player.minecraft_uuid,region:player.region,points:player.points,retired:Boolean(player.retired),created_at:player.created_at,joinedAt:player.created_at,tiers:player.tiers||{},history:player.history||[]});
const byPoints=(a,b)=>b.points-a.points||a.username.localeCompare(b.username);
const byMode=mode=>(a,b)=>(tierPoints[b.tiers?.[mode]]||0)-(tierPoints[a.tiers?.[mode]]||0)||byPoints(a,b);
const profile=(player,rank)=>({...cleanPlayer(player),...(rank?{rank}: {})});
async function body(req){let text='';for await(const part of req){text+=part;if(text.length>1_000_000)throw new Error('Requête trop grande')}return text?JSON.parse(text):{}}
async function admin(req,res){const db=await readDb();const ip=ipOf(req);if(!isLocal(ip)&&!db.adminIps.includes(ip))return send(res,403,{ok:false,error:`IP non autorisée : ${ip||'inconnue'}`});const payload=await body(req);const action=payload.action;
 if(action==='add_player'||action==='update_player'){const input=payload.player||{};const username=String(input.username||'').trim();const minecraft_uuid=String(input.minecraft_uuid||'').replaceAll('-','').trim().toLowerCase();if(!validUsername(username)||!validUuid(minecraft_uuid))return send(res,400,{ok:false,error:'Pseudo ou UUID invalide'});const duplicate=db.players.find(p=>(p.username.toLowerCase()===username.toLowerCase()||p.minecraft_uuid===minecraft_uuid)&&p.id!==payload.id);if(duplicate)return send(res,409,{ok:false,error:'Ce pseudo ou cet UUID existe déjà'});const values={username,minecraft_uuid,region:['EU','NA','AS','SA'].includes(input.region)?input.region:'EU',retired:Boolean(input.retired)};if(action==='add_player'){const player={id:randomUUID(),...values,points:0,created_at:new Date().toISOString(),tiers:{},history:[]};db.players.push(player);await saveDb(db);return send(res,201,{ok:true,id:player.id})}const player=db.players.find(p=>p.id===payload.id);if(!player)return send(res,404,{ok:false,error:'Profil introuvable'});Object.assign(player,values);updatePoints(player);await saveDb(db);return send(res,200,{ok:true,id:player.id})}
 const player=db.players.find(p=>p.id===payload.player_id||p.id===payload.id);if(action==='delete_player'){if(!player)return send(res,404,{ok:false,error:'Profil introuvable'});db.players=db.players.filter(p=>p.id!==player.id);await saveDb(db);return send(res,200,{ok:true})}
 if(action==='set_tier'||action==='remove_tier'){if(!player)return send(res,404,{ok:false,error:'Profil introuvable'});if(!/^[a-z-]{2,24}$/.test(String(payload.mode_id||'')))return send(res,400,{ok:false,error:'Mode invalide'});if(action==='remove_tier')delete player.tiers[payload.mode_id];else {const tier=String(payload.tier||'').split(' ')[0];if(!(tier in tierPoints))return send(res,400,{ok:false,error:'Tier invalide'});player.tiers[payload.mode_id]=tier}updatePoints(player);await saveDb(db);return send(res,200,{ok:true,points:player.points})}
 return send(res,400,{ok:false,error:'Action non autorisée'});
}
async function staticFile(req,res){let url=new URL(req.url,'http://localhost').pathname;if(url==='/api')return send(res,200,apiDocs);url=url==='/'?'/index.html':url;let path=normalize(join(dist,url));if(!path.startsWith(dist))return send(res,403,{error:'Interdit'});try{if((await stat(path)).isDirectory())path=join(dist,'index.html');res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream'});createReadStream(path).pipe(res)}catch{try{const file=join(dist,'index.html');res.writeHead(200,{'Content-Type':types['.html']});createReadStream(file).pipe(res)}catch{send(res,503,{error:'Lance npm run build puis npm start.'})}}}
createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname,parts=pathname.split('/').filter(Boolean);if(req.method==='GET'&&pathname==='/api/health')return send(res,200,{ok:true,service:'WorldTiers API'});if(req.method==='GET'&&pathname==='/api/modes')return send(res,200,modeIds);const db=await readDb();const all=[...db.players].sort(byPoints);if(req.method==='GET'&&(pathname==='/api/players'||pathname==='/api/top100'))return send(res,200,all.slice(0,pathname==='/api/top100'?100:all.length).map((player,index)=>profile(player,index+1)));if(req.method==='GET'&&pathname==='/api/stats')return send(res,200,{players:all.length,activePlayers:all.filter(p=>!p.retired).length,totalPoints:all.reduce((total,p)=>total+p.points,0),modes:Object.fromEntries(modeIds.map(mode=>[mode,all.filter(p=>p.tiers?.[mode]).length]))});if(req.method==='GET'&&parts[0]==='api'&&parts[1]==='user'&&parts[2]){const player=all.find(p=>p.username.toLowerCase()===decodeURIComponent(parts[2]).toLowerCase());return player?send(res,200,profile(player,all.indexOf(player)+1)):send(res,404,{error:'Joueur introuvable'})}if(req.method==='GET'&&parts[0]==='api'&&modeIds.includes(parts[1])){const mode=parts[1],ranked=all.filter(p=>p.tiers?.[mode]).sort(byMode(mode));if(parts[2]==='user'&&parts[3]){const player=ranked.find(p=>p.username.toLowerCase()===decodeURIComponent(parts[3]).toLowerCase());return player?send(res,200,{...profile(player,ranked.indexOf(player)+1),mode,tier:player.tiers[mode],modePoints:tierPoints[player.tiers[mode]]}):send(res,404,{error:'Joueur non classé dans ce mode'})}return send(res,200,ranked.map((player,index)=>({...profile(player,index+1),mode,tier:player.tiers[mode],modePoints:tierPoints[player.tiers[mode]]})))}if(req.method==='GET'&&pathname.startsWith('/api/minecraft/')){const username=decodeURIComponent(pathname.slice('/api/minecraft/'.length));if(!validUsername(username))return send(res,400,{error:'Pseudo Minecraft invalide'});const response=await fetch(`https://api.mojang.com/users/profiles/minecraft/${encodeURIComponent(username)}`);if(response.status===204||response.status===404)return send(res,404,{error:'Pseudo Minecraft introuvable'});if(!response.ok)throw new Error('Mojang indisponible');const player=await response.json();return send(res,200,{username:player.name,uuid:player.id})}if(req.method==='POST'&&pathname==='/api/admin')return admin(req,res);return staticFile(req,res)}catch(error){console.error(error);send(res,500,{ok:false,error:'Erreur serveur'})}}).listen(process.env.PORT||3001,'0.0.0.0',()=>console.log(`WorldTiers: http://localhost:${process.env.PORT||3001}`));
