import React from 'react';
import {MODES,getMode} from '../config/modes';
import {skinRenderUrl,handleProfileSkinError} from '../services/skinService';
import {getRank} from '../services/rankingService';
import {TierBadge} from '../components/ranking/TierBadge';
import {ModeIcon} from '../components/common/ModeIcon';
const skinOptions={pose:'confidence',width:600,height:600};
const profileRoles=player=>{const definitions={friend:['✦','Ami'],tester:['🧪','Testeur'],goat:['🐐','GOAT'],verified:['✓','Joueur vérifié'],media:['◉','Média']};const roles=(player.roles||[]).filter(role=>definitions[role]).map(role=>[role,...definitions[role]]);const name=player.username.toLowerCase();if(name==='belyxzor')roles.unshift(['owner','👑','Propriétaire WorldTiers'],['developer','⚙','Développeur']);if(name==='just_iyed2best')roles.unshift(['owner','👑','Propriétaire WorldTiers']);return roles};
export function PlayerPage({player,navigate}){const skin=skinRenderUrl(player,skinOptions),roles=profileRoles(player);return <main className="player-page"><button className="back" onClick={()=>history.back()}>← Retour au classement</button><section className="player-hero"><div className="skin-stage"><div className="halo"/><img src={skin} onError={event=>handleProfileSkinError(event,skinOptions)} alt={`Skin 3D de ${player.username}`}/></div><div className="player-summary"><small>JOUEUR CLASSÉ #{getRank(player)}</small><h1>{player.username}</h1>{roles.length>0&&<div className="profile-roles">{roles.map(([id,icon,label])=><span className={`profile-role ${id}`} key={id}><i>{icon}</i><b>{label}</b></span>)}</div>}<div className="player-meta"><span className={`region ${player.region.toLowerCase()}`}>{player.region}</span>{player.retired&&<span>Retraité</span>}</div><strong>{player.points}<em>points</em></strong><p>Membre du classement depuis le {new Date(player.joinedAt||player.created_at).toLocaleDateString('fr-FR')}.</p></div></section><section className="player-content"><article><h2>Tiers validés</h2><div className="tier-cards">{MODES.map(mode=><button key={mode.id} onClick={()=>navigate(`/mode/${mode.id}`)}><ModeIcon mode={mode}/><span><b>{mode.name}</b><small>{mode.description}</small></span><TierBadge modeId={mode.id} tier={player.tiers[mode.id]} wide/></button>)}</div></article><aside><h2>Historique des tests</h2><div className="history-list">{player.history.map((item,index)=>{const mode=getMode(item.mode);return <div key={index}><ModeIcon mode={mode} size="sm"/><span><b>{mode.name}</b><small>Testé par {item.tester} · {item.date}</small></span><TierBadge modeId={item.mode} tier={item.tier}/></div>})}</div></aside></section></main>}
