import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, Client, EmbedBuilder, GatewayIntentBits, PermissionFlagsBits } from 'discord.js';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=dirname(dirname(fileURLToPath(import.meta.url))),file=join(root,'data','discord-bot.json');
const api=(process.env.WORLDTIERS_API_URL||'https://worldtiers.ddns.net/api').replace(/\/$/,'');
const modes=['crystal','sword','uhc','nethpot','pot','smp','axe','diasmp','mace','spear-mace'];
const tiers=['HT1','LT1','HT2','LT2','HT3','LT3','HT4','LT4','HT5','LT5'];
let settings={};try{settings=JSON.parse(await readFile(file,'utf8'))}catch{}
const cfg=id=>{const config=settings[id]||={};config.links||={};config.testerModes||={};config.requests||={};config.panels||={};return config;},save=async()=>{await mkdir(dirname(file),{recursive:true});await writeFile(file,JSON.stringify(settings,null,2));};
const embed=(title,description,color=0x45b8ff)=>new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).setTimestamp().setFooter({text:'WorldTiers'});
const botPost=(path,body)=>fetch(`${api}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.BOT_API_SECRET||''}`},body:JSON.stringify(body)});
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers]});
const tester=async(member,config)=>Boolean(config.testerRole&&member.roles.cache.has(config.testerRole));
const requestForChannel=(config,id)=>Object.values(config.requests||{}).find(request=>request.testChannelId===id&&request.state==='testing');
const panelEmbed=panel=>embed('Tiers · File de test',`**Testeur :** <@${panel.testerId}>\n**Modes :** ${panel.modes.map(mode=>`\`${mode}\``).join(' ')}\n\n**File d’attente**\n${[0,1,2,3,4].map(index=>`${index+1}. ${panel.users[index]?`<@${panel.users[index]}>`:'—'}`).join('\n')}`,0x9b6cff);

async function syncDiscordRole(member,config){
 const username=config.links?.[member.id];if(!username||!config.testerRole||!process.env.BOT_API_SECRET)return;
 await botPost('/bot/roles',{username,role:'tester',enabled:member.roles.cache.has(config.testerRole)});
}
client.once('ready',()=>{console.log(`WorldTiers Bot connecté : ${client.user.tag}`);syncSiteRoles();setInterval(syncSiteRoles,120000);});
client.on('guildMemberAdd',async member=>{const config=cfg(member.guild.id),channel=await member.guild.channels.fetch(config.welcome).catch(()=>null);if(channel?.isTextBased())channel.send({embeds:[embed('Bienvenue !',`Bienvenue ${member} ! Utilise **/link** puis **/tierrequest** pour demander un test.`)]});});
client.on('guildMemberUpdate',(_,member)=>syncDiscordRole(member,cfg(member.guild.id)).catch(console.error));

async function syncSiteRoles(){
 for(const guild of client.guilds.cache.values())try{const config=cfg(guild.id);if(process.env.BOT_API_SECRET){const response=await botPost('/bot/links',{}),data=await response.json();if(response.ok)config.links=Object.fromEntries(data.links.map(link=>[link.discord_id,link.username]));}if(!config.testerRole)continue;const players=await (await fetch(`${api}/players`)).json();for(const [discordId,username] of Object.entries(config.links||{})){const member=await guild.members.fetch(discordId).catch(()=>null),player=players.find(item=>item.username.toLowerCase()===username.toLowerCase());if(!member||!player)continue;const enabled=(player.roles||[]).includes('tester'),has=member.roles.cache.has(config.testerRole);if(enabled&&!has)await member.roles.add(config.testerRole,'Rôle Testeur WorldTiers');if(!enabled&&has)await member.roles.remove(config.testerRole,'Synchronisation WorldTiers');}}catch(error){console.error('Synchronisation des rôles:',error.message)}
}

client.on('interactionCreate',async interaction=>{
 try{
  if(interaction.isButton()){
   if(interaction.customId.startsWith('wt_queue_')){const config=cfg(interaction.guild.id),id=interaction.customId.slice('wt_queue_'.length),panel=config.panels?.[id];if(!panel)return interaction.reply({content:'Ce panneau n’existe plus.',ephemeral:true});if(!config.links[interaction.user.id])return interaction.reply({content:'Lie d’abord ton profil Minecraft avec `/link <pseudo>`.',ephemeral:true});if(panel.users.includes(interaction.user.id))return interaction.reply({content:'Tu es déjà dans cette file.',ephemeral:true});if(panel.users.length>=5)return interaction.reply({content:'La file est complète.',ephemeral:true});panel.users.push(interaction.user.id);await save();return interaction.update({embeds:[panelEmbed(panel)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`wt_queue_${id}`).setLabel(`Entrer dans la file (${panel.users.length}/5)`).setStyle(ButtonStyle.Primary))]});}
   if(!interaction.customId.startsWith('wt_claim_'))return;const config=cfg(interaction.guild.id),id=interaction.customId.slice('wt_claim_'.length),request=config.requests?.[id];if(!request||request.state!=='queued')return interaction.reply({content:'Cette demande n’est plus disponible.',ephemeral:true});const member=await interaction.guild.members.fetch(interaction.user.id);if(!await tester(member,config))return interaction.reply({content:'Seuls les testeurs peuvent prendre une demande.',ephemeral:true});if(!(config.testerModes?.[interaction.user.id]||[]).includes(request.mode))return interaction.reply({content:`Choisis d’abord ce mode avec /testermodes : ${request.mode}`,ephemeral:true});
   const overwrites=[{id:interaction.guild.id,deny:[PermissionFlagsBits.ViewChannel]},{id:request.userId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:interaction.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}];if(config.staff)overwrites.push({id:config.staff,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const channel=await interaction.guild.channels.create({name:`test-${request.mode}-${request.username}`.toLowerCase().replace(/[^a-z0-9-]/g,''),type:ChannelType.GuildText,parent:config.testCategory||undefined,permissionOverwrites:overwrites});request.state='testing';request.testerId=interaction.user.id;request.testerName=interaction.user.username;request.testChannelId=channel.id;await save();await channel.send({content:`<@${request.userId}> <@${request.testerId}>`,embeds:[embed(`Test ${request.mode}`,`**Joueur :** ${request.username}\n**Testeur :** ${interaction.user.username}\nÀ la fin : `/testaccept <tier>` ou `/testreject <raison>`.`)]});return interaction.update({embeds:[embed(`Demande prise · ${request.mode}`,`${request.username} est maintenant testé par ${interaction.user}.`,0x57f287)],components:[]});
  }
  if(!interaction.isChatInputCommand()||!interaction.guild)return;const config=cfg(interaction.guild.id),reply=payload=>interaction.reply({...payload,ephemeral:true});
  if(interaction.commandName==='setup'){config.announcements=interaction.options.getChannel('annonces',true).id;config.welcome=interaction.options.getChannel('bienvenue')?.id||null;config.tickets=interaction.options.getChannel('tickets')?.id||null;config.staff=interaction.options.getRole('staff')?.id||null;await save();return reply({embeds:[embed('Bot configuré','Salons WorldTiers enregistrés.')]});}
  if(interaction.commandName==='testconfig'){config.queue=interaction.options.getChannel('file',true).id;config.testCategory=interaction.options.getChannel('categorie',true).id;config.testerRole=interaction.options.getRole('testeurs',true).id;await save();return reply({embeds:[embed('Système de tests prêt','Les joueurs peuvent utiliser /tierrequest et les testeurs /testermodes.')]});}
  if(interaction.commandName==='link'){const username=interaction.options.getString('joueur',true),response=await botPost('/bot/link/start',{username,discord_id:interaction.user.id}),data=await response.json();if(!response.ok)return reply({content:data.error||'Profil WorldTiers introuvable.'});return reply({embeds:[embed('Confirmation Minecraft requise',`Connecte-toi avec **${username}** dans Minecraft, puis écris :\n\n\`/worldtiers link ${data.code}\`\n\nCe code expire dans 15 minutes.`,0xf4b942)]});}
  if(interaction.commandName==='rolesync'){await syncDiscordRole(await interaction.guild.members.fetch(interaction.user.id),config);return reply({content:'Rôle Testeur synchronisé.'});}
  if(interaction.commandName==='testermodes'){const member=await interaction.guild.members.fetch(interaction.user.id);if(!await tester(member,config))return reply({content:'Tu dois avoir le rôle Discord Testeur.'});const chosen=[...new Set(interaction.options.getString('modes',true).toLowerCase().split(',').map(mode=>mode.trim()).filter(mode=>modes.includes(mode)))];if(!chosen.length)return reply({content:`Aucun mode valide. Modes : ${modes.join(', ')}`});config.testerModes[interaction.user.id]=chosen;await save();return reply({embeds:[embed('Modes de test enregistrés',chosen.map(mode=>`• ${mode}`).join('\n'))]});}
  if(interaction.commandName==='tierpanel'){const member=await interaction.guild.members.fetch(interaction.user.id);if(!await tester(member,config))return reply({content:'Tu dois avoir le rôle Discord Testeur pour créer une file.'});const selected=[...new Set(interaction.options.getString('modes',true).toLowerCase().split(',').map(mode=>mode.trim()).filter(mode=>modes.includes(mode)))];if(!selected.length)return reply({content:`Aucun mode valide. Modes : ${modes.join(', ')}`});const id=crypto.randomUUID(),panel={id,testerId:interaction.user.id,modes:selected,users:[]};const message=await interaction.channel.send({embeds:[panelEmbed(panel)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`wt_queue_${id}`).setLabel('Entrer dans la file (0/5)').setStyle(ButtonStyle.Primary))]});panel.messageId=message.id;panel.channelId=interaction.channelId;config.panels[id]=panel;await save();return reply({content:'Panneau de file créé dans ce salon.'});}
  if(interaction.commandName==='testsetup'||interaction.commandName==='tierrequest'){let queueId=config.queue,playerId=interaction.user.id,username=config.links[playerId],mode=interaction.options.getString('mode',true).toLowerCase();if(interaction.commandName==='testsetup'){const member=await interaction.guild.members.fetch(interaction.user.id);if(!await tester(member,config))return reply({content:'Tu dois avoir le rôle Discord Testeur pour ajouter un joueur.'});queueId=interaction.options.getChannel('file',true).id;playerId=interaction.options.getUser('joueur',true).id;username=config.links[playerId];}if(!username)return reply({content:'Ce joueur doit d’abord lier son compte avec /link <pseudo>.'});if(!modes.includes(mode))return reply({content:`Mode invalide. Modes : ${modes.join(', ')}`});const queue=await interaction.guild.channels.fetch(queueId).catch(()=>null);if(!queue?.isTextBased())return reply({content:'Salon de file invalide.'});const id=crypto.randomUUID(),message=await queue.send({embeds:[embed(`Demande de test · ${mode}`,`**Joueur :** ${username}\nLes testeurs disponibles peuvent prendre cette demande.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`wt_claim_${id}`).setLabel('Prendre le test').setStyle(ButtonStyle.Primary))]});config.requests[id]={id,messageId:message.id,userId:playerId,username,mode,state:'queued',createdAt:new Date().toISOString()};await save();return reply({content:`La demande **${mode}** de **${username}** est dans la file d’attente.`});}
  if(interaction.commandName==='testaccept'||interaction.commandName==='testreject'){const request=requestForChannel(config,interaction.channelId);if(!request)return reply({content:'Cette commande doit être utilisée dans un salon de test actif.'});const member=await interaction.guild.members.fetch(interaction.user.id);if(interaction.user.id!==request.testerId&&!await tester(member,config))return reply({content:'Seul le testeur assigné peut terminer ce test.'});if(interaction.commandName==='testreject'){request.state='rejected';request.reason=interaction.options.getString('raison',true);await save();return interaction.reply({embeds:[embed('Test refusé',request.reason,0xed4245)]});}const tier=interaction.options.getString('tier',true).toUpperCase();if(!tiers.includes(tier))return reply({content:`Tier invalide : ${tiers.join(', ')}`});const response=await botPost('/bot/test-result',{username:request.username,mode_id:request.mode,tier,tester:interaction.user.username}),data=await response.json();if(!response.ok)return reply({content:data.error||'Impossible de valider le tier.'});request.state='validated';request.tier=tier;await save();return interaction.reply({embeds:[embed('Tier validé',`**${request.username}** obtient **${tier}** en ${request.mode}. Total : **${data.points} pts**`,0x57f287)]});}
  if(['rank','profil'].includes(interaction.commandName)){const name=interaction.options.getString('joueur',true),r=await fetch(`${api}/user/${encodeURIComponent(name)}`),p=await r.json();if(!r.ok)return reply({content:'Joueur introuvable.'});const list=Object.entries(p.tiers||{}).map(([mode,tier])=>`• ${mode} : **${tier}**`).join('\n')||'Aucun tier validé.';return reply({embeds:[embed(`${p.username} · #${p.rank}`,`**${p.points} points** · ${p.region}\n${list}`).setURL(`${api.replace(/\/api$/,'')}/player/${encodeURIComponent(p.username)}`)]});}
  if(interaction.commandName==='top'){const mode=(interaction.options.getString('mode')||'top100').toLowerCase();if(mode!=='top100'&&!modes.includes(mode))return reply({content:'Mode invalide.'});const players=await (await fetch(`${api}/${mode}`)).json();return reply({embeds:[embed(`Top ${mode==='top100'?'global':mode}`,players.slice(0,10).map((p,i)=>`**${i+1}.** ${p.username} — ${p.points} pts`).join('\n')||'Aucun joueur classé.')]});}
  if(interaction.commandName==='ticket'){const subject=interaction.options.getString('sujet',true),overwrites=[{id:interaction.guild.id,deny:[PermissionFlagsBits.ViewChannel]},{id:interaction.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}];if(config.staff)overwrites.push({id:config.staff,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const channel=await interaction.guild.channels.create({name:`ticket-${interaction.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,''),type:ChannelType.GuildText,parent:config.tickets||undefined,permissionOverwrites:overwrites});await channel.send({embeds:[embed('Ticket WorldTiers',`Créé par ${interaction.user}\n**Sujet :** ${subject}`)]});return reply({content:`Ticket créé : ${channel}`});}
  if(interaction.commandName==='close'){if(!interaction.channel?.name.startsWith('ticket-'))return reply({content:'Cette commande doit être utilisée dans un ticket.'});await reply({content:'Fermeture dans 5 secondes.'});return setTimeout(()=>interaction.channel.delete('Ticket fermé').catch(()=>{}),5000);}
  if(interaction.commandName==='announce'){const message=interaction.options.getString('message',true),channel=config.announcements&&await interaction.guild.channels.fetch(config.announcements).catch(()=>null);if(!channel?.isTextBased())return reply({content:'Utilise /setup pour choisir le salon des annonces.'});await channel.send({embeds:[embed('Mise à jour WorldTiers',message)]});if(process.env.BOT_API_SECRET)await botPost('/bot/announcement',{message,author:interaction.user.username});return reply({content:'Annonce publiée.'});}
  if(['warn','kick','ban'].includes(interaction.commandName)){const user=interaction.options.getUser('membre',true),reason=interaction.options.getString('raison',true),member=await interaction.guild.members.fetch(user.id).catch(()=>null);if(interaction.commandName==='warn')return reply({embeds:[embed('Avertissement',`${user} — ${reason}`,0xf4b942)]});if(!member)return reply({content:'Membre introuvable.'});if(interaction.commandName==='kick')await member.kick(reason);else await member.ban({reason});return reply({embeds:[embed(interaction.commandName==='ban'?'Membre banni':'Membre expulsé',`${user} — ${reason}`,0xed4245)]});}
 }catch(error){console.error(error);if(interaction.isRepliable()&&!interaction.replied)interaction.reply({content:'Une erreur est survenue. Vérifie les permissions et la configuration.',ephemeral:true}).catch(()=>{});}
});
if(!process.env.DISCORD_TOKEN)throw new Error('DISCORD_TOKEN manquant dans .env');
client.login(process.env.DISCORD_TOKEN);
